-- ============================================================
-- Seed del catalogo de smoke tests (38 casos, separados por shell).
-- Correr DESPUES de schema.sql, una sola vez, en el SQL Editor de Supabase.
-- Idempotente: on conflict (id) do nothing.
-- ============================================================

insert into public.cases
  (id, groups, module, impl, title, feature, precond, data, steps, expected, warn, flag, sort)
values
  ('CORP-E2E-01', array['corp'], 'MF+Worker', 'impl', 'Baja manual de SellerMarketplace → el worker restaura la integración (~10 min)', 'E2E worker + tracking + reconciliación', 'Usuario corporativo con integración activa (ej. Frávega). Acceso a la DB.', 'Borrar la row de SellerMarketplace (Frávega) · esperar el ciclo del worker (300s) hasta 2 vueltas', '["Loguearse (aecom-test@yopmail.com) y ver Panel de Integraciones con Frávega + Cetrogar en Integrado.","Eliminar en la DB la row SellerMarketplace de Frávega. Refrescar: Frávega vuelve a Disponible.","Esperar ~10 min (ciclos del worker). Refrescar."]'::jsonb, '["Tras la baja, Frávega aparece Disponible (integración perdida).","El worker detecta un envío del seller bajo el contrato de Frávega vía tracking hub y re-inserta/reactiva la relación.","La integración vuelve a Integrado sin intervención manual. (Evidencia 07-2026: restauró a los 10 min.)"]'::jsonb, null, true, 0),
  ('MF-AUTH-01-CORP', array['corp'], 'MF', 'impl', 'Bootstrap recibe auth y decide vista (Marketplace vs Seller)', 'Bootstrap / auth (src/bootstrap/App.tsx)', 'MF montado por un shell (o harness standalone) con prop auth válida.', 'auth.marketplaceId truthy → Marketplace · null/"" → Seller', '["Montar con auth.marketplaceId presente.","Repetir con auth.marketplaceId null/vacío."]'::jsonb, '["Con marketplaceId → MarketplacePage (data-testid=\"marketplace-app\").","Sin marketplaceId → SellerPage (data-testid=\"seller-app\").","En ambos, localStorage[\"fullcommerce:token\"] queda con auth.token.token."]'::jsonb, null, false, 1),
  ('MF-AUTH-01-PYME', array['pyme'], 'MF', 'impl', 'Bootstrap recibe auth y decide vista (Marketplace vs Seller)', 'Bootstrap / auth (src/bootstrap/App.tsx)', 'MF montado por un shell (o harness standalone) con prop auth válida.', 'auth.marketplaceId truthy → Marketplace · null/"" → Seller', '["Montar con auth.marketplaceId presente.","Repetir con auth.marketplaceId null/vacío."]'::jsonb, '["Con marketplaceId → MarketplacePage (data-testid=\"marketplace-app\").","Sin marketplaceId → SellerPage (data-testid=\"seller-app\").","En ambos, localStorage[\"fullcommerce:token\"] queda con auth.token.token."]'::jsonb, null, false, 2),
  ('MF-SELLERS-01', array['corp'], 'MF', 'impl', 'Grilla de sellers carga desde API', 'Marketplace Sellers grid', 'Vista Marketplace · token REST válido · API arriba.', 'GET /api/v1/Marketplace/sellers?Page=1&PageSize=10', '["Entrar como marketplace y abrir vista Sellers (KPI \"Sellers totales\").","Observar la request."]'::jsonb, '["Loading: fila con CircularProgress.","Success: filas con nombre + estado (Pills) + paginación server.","Empty: \"No hay sellers para mostrar.\"","Error: \"No pudimos cargar los sellers. Intenta nuevamente.\""]'::jsonb, null, false, 3),
  ('MF-SELLERS-02', array['corp'], 'MF', 'impl', 'Filtro por estado (Activa / Inactiva)', 'Marketplace Sellers grid', 'Grilla cargada.', 'Status=Activa / Status=Inactiva', '["Seleccionar filtro Activa.","Seleccionar Inactiva."]'::jsonb, '["La request incluye Status y refetchea con overlay de loading.","Solo se muestran sellers del estado elegido."]'::jsonb, null, false, 4),
  ('MF-SELLERS-03', array['corp'], 'MF', 'impl', 'Búsqueda + paginación + page size', 'Marketplace Sellers grid', 'Grilla con más de una página.', 'Page size 5 / 10 / 20', '["Buscar un fragmento de nombre/email.","Cambiar page size (5→20).","Navegar entre páginas."]'::jsonb, '["Búsqueda filtra CLIENT-SIDE sobre la página cargada (el server no tiene param Search).","Cambiar page size dispara nueva request.","Paginación avanza/retrocede."]'::jsonb, 'Quirk conocido: durante la búsqueda el count de paginación usa solo el largo filtrado.', false, 5),
  ('MF-INTEG-01-CORP', array['corp'], 'MF', 'impl', 'Listado de integraciones (hechas + disponibles)', 'GestionIntegraciones.tsx', 'Vista Seller · token REST válido.', 'GET /api/v1/Integrations', '["Entrar como seller/pyme (marketplaceId vacío).","Observar la carga."]'::jsonb, '["Cards \"Integrado\" deshabilitadas + disponibles clickeables (→ detalle)."]'::jsonb, 'GestionIntegraciones NO renderiza loading/error/empty explícitos; solo mapea arrays.', false, 6),
  ('MF-INTEG-01-PYME', array['pyme'], 'MF', 'impl', 'Listado de integraciones (hechas + disponibles)', 'GestionIntegraciones.tsx', 'Vista Seller · token REST válido.', 'GET /api/v1/Integrations', '["Entrar como seller/pyme (marketplaceId vacío).","Observar la carga."]'::jsonb, '["Cards \"Integrado\" deshabilitadas + disponibles clickeables (→ detalle)."]'::jsonb, 'GestionIntegraciones NO renderiza loading/error/empty explícitos; solo mapea arrays.', false, 7),
  ('MF-INTEG-02-CORP', array['corp'], 'MF', 'impl', 'Solicitar código (request-code)', 'IngresoMail.tsx', 'En detalle de una integración disponible.', 'POST /Integrations/request-code {marketplaceId, sellerEmail}', '["Ingresar email válido (pasa regex).","Enviar."]'::jsonb, '["codeRequired=true → vista verificacion-codigo.","codeRequired=false (mail Andreani) → felicitaciones.","Toast de éxito (solo standalone Next, no federado).","Email inválido → error inline, sin request."]'::jsonb, null, false, 8),
  ('MF-INTEG-02-PYME', array['pyme'], 'MF', 'impl', 'Solicitar código (request-code)', 'IngresoMail.tsx', 'En detalle de una integración disponible.', 'POST /Integrations/request-code {marketplaceId, sellerEmail}', '["Ingresar email válido (pasa regex).","Enviar."]'::jsonb, '["codeRequired=true → vista verificacion-codigo.","codeRequired=false (mail Andreani) → felicitaciones.","Toast de éxito (solo standalone Next, no federado).","Email inválido → error inline, sin request."]'::jsonb, null, false, 9),
  ('MF-INTEG-03-CORP', array['corp'], 'MF', 'impl', 'Confirmar código (confirm-code)', 'VerificacionCodigo.tsx', 'Vino de request-code con codeRequired=true.', 'POST /Integrations/confirm-code {marketplaceId, code}', '["Ingresar código de 6 dígitos (tipeo, paste, auto-advance).","Probar código incorrecto y correcto.","Esperar timer 5 min → reenviar."]'::jsonb, '["Correcto → felicitaciones.","Incorrecto → banner \"El código ingresado es incorrecto\" + limpia dígitos.","Timer a 0 → habilita reenvío (re-llama request-code)."]'::jsonb, null, false, 10),
  ('MF-INTEG-03-PYME', array['pyme'], 'MF', 'impl', 'Confirmar código (confirm-code)', 'VerificacionCodigo.tsx', 'Vino de request-code con codeRequired=true.', 'POST /Integrations/confirm-code {marketplaceId, code}', '["Ingresar código de 6 dígitos (tipeo, paste, auto-advance).","Probar código incorrecto y correcto.","Esperar timer 5 min → reenviar."]'::jsonb, '["Correcto → felicitaciones.","Incorrecto → banner \"El código ingresado es incorrecto\" + limpia dígitos.","Timer a 0 → habilita reenvío (re-llama request-code)."]'::jsonb, null, false, 11),
  ('MF-SHIP-01', array['corp'], 'MF', 'impl', 'Grilla de envíos vía SignalR', 'MarketplaceSellerShipments.tsx', 'Branch NTGRCNS-562 · token LARGO B2C en localStorage["token"] · hub de tracking accesible.', 'Hub TrackingSubscribeState · evento sendTracking · seller pruebacorpo24 (94 envíos) · userId="" · 30 días', '["Abrir la vista de envíos de un seller.","Observar: WebSocket (skipNegotiation) → send → sendTracking.","Cambiar el rango Desde."]'::jsonb, '["Conecta por WebSockets directo (sin negotiate).","Muestra hasta 50 filas (cap del hub) + aviso \"Mostrando N de M\".","Cambiar fecha resetea a página 0 y re-suscribe.","userId debe ir VACÍO (el GUID no mapea en el elastic de tracking)."]'::jsonb, 'Vive solo en branch NTGRCNS-562 (PR #25, draft). No está en develop.', false, 12),
  ('MF-SHIP-02', array['corp'], 'MF', 'impl', 'Estados UX de la grilla de envíos (loading / empty / timeout)', 'Grilla de envíos — estados', 'Igual que MF-SHIP-01.', 'Timeout de respuesta (default de useHubSubscription)', '["Cargar con conexión OK pero sin datos (seller sin envíos en la ventana).","Cortar red tras conectar para gatillar el timeout."]'::jsonb, '["Loading: \"Recuperando envíos\".","Empty: mensaje de sin resultados.","Timeout: banner de error (por timeout, no por rechazo de send).","Sin flashes ni doble-suscripción al reconectar."]'::jsonb, 'Vive solo en branch NTGRCNS-562.', false, 13),
  ('MF-DASH-01-CORP', array['corp'], 'MF', 'mock', 'Dashboard / Ver métricas (KPIs y gráficos)', 'DashboardGeneral / DashboardSeller / charts', '—', '—', '["Click en \"Ver métricas\" desde el Panel de Integraciones."]'::jsonb, '["Se ve el dashboard, PERO todos los KPIs, envíos por seller, zonas y modalidades salen de dashboard.constants.ts (MOCK_*, Math.random()).","No hay fuente real ni loading/error/empty. DashboardSeller (detalle) es además inalcanzable."]'::jsonb, 'MOCKEADO — no valida integración. Marcar OK solo cuando exista API de métricas real.', false, 14),
  ('MF-DASH-01-PYME', array['pyme'], 'MF', 'mock', 'Dashboard / Ver métricas (KPIs y gráficos)', 'DashboardGeneral / DashboardSeller / charts', '—', '—', '["Click en \"Ver métricas\" desde el Panel de Integraciones."]'::jsonb, '["Se ve el dashboard, PERO todos los KPIs, envíos por seller, zonas y modalidades salen de dashboard.constants.ts (MOCK_*, Math.random()).","No hay fuente real ni loading/error/empty. DashboardSeller (detalle) es además inalcanzable."]'::jsonb, 'MOCKEADO — no valida integración. Marcar OK solo cuando exista API de métricas real.', false, 15),
  ('MF-COMO-01-CORP', array['corp'], 'MF', 'stub', 'Pantalla "Cómo integrar"', 'ComoIntegrar.tsx', '—', '—', '["Entrar por \"Conocer más\" desde IngresoMail."]'::jsonb, '["Solo renderiza el título. El cuerpo (descripción, secciones, FAQs, dropdowns) está COMENTADO (ComoIntegrar.tsx:52, :77-107).","El contenido (MARKETPLACES en constanst/integraciones.ts) está huérfano."]'::jsonb, 'STUB — solo testeable el título + botón volver.', false, 16),
  ('MF-COMO-01-PYME', array['pyme'], 'MF', 'stub', 'Pantalla "Cómo integrar"', 'ComoIntegrar.tsx', '—', '—', '["Entrar por \"Conocer más\" desde IngresoMail."]'::jsonb, '["Solo renderiza el título. El cuerpo (descripción, secciones, FAQs, dropdowns) está COMENTADO (ComoIntegrar.tsx:52, :77-107).","El contenido (MARKETPLACES en constanst/integraciones.ts) está huérfano."]'::jsonb, 'STUB — solo testeable el título + botón volver.', false, 17),
  ('MF-FELIZ-01-CORP', array['corp'], 'MF', 'stub', 'CTA "Ver mis envíos" post-integración', 'Felicitaciones.tsx', 'Integración confirmada.', '—', '["Completar una integración y llegar a Felicitaciones.","Click en \"Ver mis envíos\"."]'::jsonb, '["El botón hace window.location.href=\"/ver-envios\" (Felicitaciones.tsx:40), ruta que NO existe → 404.","El resto de la pantalla (nombre, email) sí es real."]'::jsonb, 'STUB en el CTA. La pantalla de felicitaciones sí es testeable.', false, 18),
  ('MF-FELIZ-01-PYME', array['pyme'], 'MF', 'stub', 'CTA "Ver mis envíos" post-integración', 'Felicitaciones.tsx', 'Integración confirmada.', '—', '["Completar una integración y llegar a Felicitaciones.","Click en \"Ver mis envíos\"."]'::jsonb, '["El botón hace window.location.href=\"/ver-envios\" (Felicitaciones.tsx:40), ruta que NO existe → 404.","El resto de la pantalla (nombre, email) sí es real."]'::jsonb, 'STUB en el CTA. La pantalla de felicitaciones sí es testeable.', false, 19),
  ('API-LOGIN-01', array['otros'], 'API', 'impl', 'Intercambio de token B2C → JWT propio', 'POST /api/v1/Login', 'Token largo B2C válido.', 'POST /api/v1/Login {token:<B2C>, clientType:1|2, destinatarioFacturaId?}', '["Enviar token B2C con clientType (1=Pyme, 2=Corporate)."]'::jsonb, '["200 + TokenResponse (JWT corto + expiración) → va a fullcommerce:token.","Token B2C inválido → 401."]'::jsonb, null, false, 20),
  ('API-AUTH-01', array['otros'], 'API', 'nofront', 'Refresh token', 'POST /api/v1/refresh', '—', 'POST /api/v1/refresh {refreshToken} (anónimo)', '["Enviar un refreshToken válido."]'::jsonb, '["200 + nuevo TokenResponse (rota refresh + emite access).","Refresh inválido/revocado → 401."]'::jsonb, 'Implementado en backend, sin consumidor front confirmado.', false, 21),
  ('API-AUTH-02', array['otros'], 'API', 'nofront', 'Logout (revoca refresh)', 'POST /api/v1/logout', 'Refresh válido.', 'POST /api/v1/logout {refreshToken}', '["Logout con refresh válido.","Intentar refresh con ese mismo token."]'::jsonb, '["200 LogoutResponse; el refresh queda revocado → el refresh posterior da 401."]'::jsonb, 'Sin consumidor front confirmado.', false, 22),
  ('API-INTEG-01', array['otros'], 'API', 'impl', 'Listar integraciones', 'GET /api/v1/Integrations', 'Token REST.', 'GET /Integrations', '["GET con token válido.","GET sin token."]'::jsonb, '["200 {integrationsDone[], integrationsAvailable[]}.","Sin token → 401."]'::jsonb, null, false, 23),
  ('API-INTEG-02', array['otros'], 'API', 'impl', 'Solicitar código de vinculación', 'POST /Integrations/request-code', 'Token REST.', 'POST /request-code {marketplaceId, sellerEmail}', '["Mail Andreani.","Mail externo."]'::jsonb, '["Mail Andreani → vincula directo (codeRequired=false).","Mail externo → envía código (codeRequired=true, TTL 5 min).","Errores: 400/404/409."]'::jsonb, null, false, 24),
  ('API-INTEG-03', array['otros'], 'API', 'impl', 'Confirmar código de vinculación', 'POST /Integrations/confirm-code', 'Código solicitado.', 'POST /confirm-code {marketplaceId, code}', '["Código válido.","Código inválido/expirado."]'::jsonb, '["Válido → 201.","Inválido/expirado → 400/409."]'::jsonb, null, false, 25),
  ('API-MKT-01', array['otros'], 'API', 'impl', 'Datos del marketplace propio', 'GET /api/v1/Marketplace', 'Usuario UserType=Marketplace.', 'GET /Marketplace', '["GET como marketplace.","GET como no-marketplace."]'::jsonb, '["200 GetMyMarketplaceResponse.","No-marketplace → 403; inexistente → 404."]'::jsonb, null, false, 26),
  ('API-MKT-02', array['otros'], 'API', 'impl', 'Sellers del marketplace (paginado)', 'GET /Marketplace/sellers', 'Token REST.', 'GET /Marketplace/sellers?Page&PageSize&Status', '["GET con paginación.","GET con Status.","GET con params inválidos."]'::jsonb, '["200 paginado; Status filtra.","Params inválidos → 400; sin auth → 401."]'::jsonb, null, false, 27),
  ('API-MKT-03', array['otros'], 'API', 'nofront', 'Pickups del marketplace', 'GET /Marketplace/pickups', 'Token REST.', 'GET /Marketplace/pickups?SellerId&Page&PageSize', '["GET con y sin SellerId."]'::jsonb, '["200 paginado informando seller + estado; filtra por SellerId."]'::jsonb, 'Sin consumidor front.', false, 28),
  ('API-PICKUP-01', array['otros'], 'API', 'nofront', 'Crear colecta(s)', 'POST /api/v1/Pickup', 'Token REST.', 'POST /Pickup {shipments[], address, contact}', '["POST con body válido.","POST con body inválido."]'::jsonb, '["201 CreatePickupResponse agrupando envíos en colectas.","Body inválido → 400."]'::jsonb, 'Sin consumidor front.', false, 29),
  ('API-CONTRACTS-01', array['otros'], 'API', 'nofront', 'Contratos del seller por email', 'GET /seller-contracts', '—', 'GET /seller-contracts?Email', '["GET con Email válido.","GET sin Email."]'::jsonb, '["Por cada marketplace activo: MarketplaceEmail + lista de contratos.","Email faltante → 400."]'::jsonb, 'Sin consumidor front. Alimenta la misma lógica que replica el worker.', false, 30),
  ('API-CONTRACTS-02', array['otros'], 'API', 'nofront', 'Contratos del seller corporativo (por CL)', 'GET /seller-contracts/corporate', '—', 'GET /seller-contracts/corporate?CL', '["GET con CL válido."]'::jsonb, '["MarketplaceEmail + contratos para el CL.","CL faltante → 400."]'::jsonb, 'Sin consumidor front.', false, 31),
  ('WK-SYNC-01', array['otros'], 'Worker', 'impl', 'Arranque y loop periódico', 'SellerSynchronizationWorker', '.NET 10 · DB de prueba · Worker:ExecutionIntervalSeconds (ej. 5s).', 'dotnet run --project src/Api/ActualizacionSellersWorker.csproj', '["Levantar con intervalo corto.","Observar logs + APM."]'::jsonb, '["Log de deployment marker al iniciar.","Cada iteración abre transacción APM seller-synchronization y loguea el resumen.","Intervalo ≤0 → excepción de config."]'::jsonb, null, false, 32),
  ('WK-SYNC-02', array['otros'], 'Worker', 'impl', 'Carga de contratos activos (Contract ⋈ Marketplace)', 'GetActiveContracts', 'DB con Contract + Marketplace.', 'c.IsDeleted=0 AND m.IsActive=1 AND m.IsDeleted=0', '["Insertar 1 contrato activo + 1 borrado.","Correr una iteración."]'::jsonb, '["Solo el activo entra al procesamiento.","Ventana: to=now, from=now - ActiveSellerLookbackDays (default 30)."]'::jsonb, null, false, 33),
  ('WK-SYNC-03', array['otros'], 'Worker', 'impl', 'Consulta al hub de tracking por contrato', 'TrackingSuscribeStateByContrato', 'Hub accesible (Tracking:HubUrl).', '{idSistema:4, idReceptor:2, contrato, from, to, esActivo:true} · evento SendTrackingByContrato', '["Con un contrato con envíos en la ventana, correr iteración.","Observar suscripción y respuesta."]'::jsonb, '["Recibe resultsList; mapea email→MarketplaceEmail, fechaPrimeraNovedad→LastShipment.","Items con email vacío se descartan.","Dedup por (ContractNo, MarketplaceEmail) con el LastShipment más reciente.","Fallo del hub → contrato cuenta como failed, el loop sigue."]'::jsonb, null, false, 34),
  ('WK-SYNC-04', array['otros'], 'Worker', 'impl', 'Alta de relación Seller-Marketplace nueva', 'SellerMarketplaceReconciler', 'Tracking devuelve un seller sin relación con ese marketplace.', 'Login API POST /api/v1/Usuario/Email para resolver nombre/CL/tipo', '["Preparar tracking con seller nuevo.","Correr iteración."]'::jsonb, '["Resuelve el Seller (por email; si no, reactiva soft-deleted; si no, Login API + insert).","Corporate sin CL resoluble → se saltea.","Inserta/reactiva SellerMarketplace → Registered.","Emails normalizados Trim().ToLowerInvariant()."]'::jsonb, null, false, 35),
  ('WK-SYNC-05', array['otros'], 'Worker', 'impl', 'Update de LastShipment (envío más reciente)', 'UpdateLastShipment (condicional)', 'Existe SellerMarketplace activo con LastShipment viejo.', 'Tracking con envío más reciente / más viejo', '["Envío más nuevo → correr iteración.","Repetir con envío más viejo."]'::jsonb, '["Más nuevo → UPDATE condicional de LastShipment → Updated; si Name vacío, SellerNameEnricher lo completa (best-effort).","Más viejo → SkippedOlderShipment (no actualiza)."]'::jsonb, null, false, 36),
  ('WK-SYNC-06', array['otros'], 'Worker', 'impl', 'Fallback a PendingSellerMarketplace', 'UpsertPendingSellerMarketplace', 'Seller no resoluble o relación ya activa.', '—', '["Forzar un seller no resoluble (corporate sin CL) o relación ya activa.","Correr iteración."]'::jsonb, '["Upsert en PendingSellerMarketplace (insert o update de LastShipment) → QueuedToPending.","No rompe el resto del procesamiento."]'::jsonb, null, false, 37)
on conflict (id) do nothing;

-- ---- Métricas (transaccional-client-metrics-api) ----
-- En desarrollo. Marcadas 'stub' (no implementado); pasar a 'nofront' cuando el
-- endpoint esté deployado y el MF deje de mockear.
insert into public.cases
  (id, groups, module, impl, title, feature, precond, data, steps, expected, warn, flag, sort)
values
  ('API-MET-01', array['otros'], 'Metrics API', 'stub',
   'Métricas Marketplace — envíos por seller por rango de fechas',
   'transaccional-client-metrics-api · endpoint marketplace',
   'Usuario marketplace · rango de fechas (desde/hasta).',
   'GET envíos por seller en el rango; discriminado por domicilio y retiro por mostrador',
   '["Llamar al endpoint con un rango de fechas.","Verificar el desglose por tipo de envío."]'::jsonb,
   '["Devuelve, por seller, la cantidad de envíos en el rango.","Cada cantidad discriminada en envío a domicilio y retiro por mostrador."]'::jsonb,
   'En desarrollo en transaccional-client-metrics-api (repo aparte). Cambiar a Sin frontend cuando el endpoint esté deployado.',
   false, 38),
  ('API-MET-02', array['otros'], 'Metrics API', 'stub',
   'Métricas Marketplace — top sellers por rango de fecha',
   'transaccional-client-metrics-api · endpoint marketplace',
   'Usuario marketplace · rango de fechas (desde/hasta).',
   'GET ranking de sellers por cantidad de envíos en el rango (sin desglose)',
   '["Llamar al endpoint con un rango de fechas.","Verificar el orden por cantidad de envíos."]'::jsonb,
   '["Devuelve el ranking de sellers por cantidad de envíos en el rango.","Solo cantidad total, sin discriminar por tipo de envío."]'::jsonb,
   'En desarrollo en transaccional-client-metrics-api (repo aparte). Cambiar a Sin frontend cuando el endpoint esté deployado.',
   false, 39),
  ('API-MET-03', array['otros'], 'Metrics API', 'stub',
   'Métricas Seller — envíos por mes (domicilio vs retiro por mostrador)',
   'transaccional-client-metrics-api · endpoint seller',
   'Usuario seller.',
   'GET cantidad de envíos por mes; discriminado por envío a domicilio y retiro por mostrador',
   '["Llamar al endpoint del seller.","Verificar el desglose mensual por tipo de envío."]'::jsonb,
   '["Devuelve la cantidad de envíos por mes.","Cada mes discriminado en envío a domicilio y retiro por mostrador."]'::jsonb,
   'En desarrollo en transaccional-client-metrics-api (repo aparte). Cambiar a Sin frontend cuando el endpoint esté deployado.',
   false, 40)
on conflict (id) do nothing;
